import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from "next/image";
import axiosClient from '@/libraries/axiosClient';
import Navbar from '@/components/Navbar/navbar'
import Slide from '@/components/Navigation/slide'
import Categories from '@/pages/categories'
import Information from '@/components/Information/Information'
import Footer from '@/components/Footer/footer'
import Hotsale from '@/components/hotSale'
import ProductSP from '@/components/productSP';
const inter = Inter({ subsets: ['latin'] })

export default function Home({ productsSale, productSP, categories }) {
  return (
    <>
      <Head>
        <title>Shop Smart Phone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={`${styles.main} `}>
          <Navbar />
          <Slide />
          
          <Categories categories={categories} />
          <Hotsale productsSale={productsSale} />
          <ProductSP productSP={productSP} />
          <hr />
          <Information />

          <Footer />


        </div>
      </div>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const response = await axiosClient.get('/user/products');
    const responseSale = await axiosClient.get('questions/hotSale');
    const responseSP = await axiosClient.get('questions/spRandom');

    const filter = await axiosClient.get('user/categories');



    return {
      props: {
        products: response.data.payload,
        productsSale: responseSale.data.payload,
        productSP: responseSP.data.payload,
        categories: filter.data.payload

      },

    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}
